// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentRoadMap.Infrastructure.Persistence;

#nullable disable

namespace StudentRoadMap.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902165954_AddAnalysisJobsAndFallbackReportFlag")]
    partial class AddAnalysisJobsAndFallbackReportFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudentRoadMap.Domain.Ai.AiAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<int>("AttemptNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("attempt_number");

                    b.Property<string>("AttentionFlagsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("attention_flags_json");

                    b.Property<string>("CareerSuggestionsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("career_suggestions_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<decimal?>("EstimatedCostUsd")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("estimated_cost_usd");

                    b.Property<string>("GrowthAreasJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("growth_areas_json");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_current");

                    b.Property<bool>("IsFallbackReport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_fallback_report");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("model");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("ParentNotes")
                        .HasColumnType("text")
                        .HasColumnName("parent_notes");

                    b.Property<string>("PersonalityPortrait")
                        .HasColumnType("text")
                        .HasColumnName("personality_portrait");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prompt_version");

                    b.Property<short>("Provider")
                        .HasColumnType("smallint")
                        .HasColumnName("provider");

                    b.Property<string>("RecommendationsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("recommendations_json");

                    b.Property<string>("RequestPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_payload_json");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_json");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("status");

                    b.Property<string>("StrengthsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("strengths_json");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("TeacherNotes")
                        .HasColumnType("text")
                        .HasColumnName("teacher_notes");

                    b.HasKey("Id")
                        .HasName("pk_ai_analyses");

                    b.HasIndex("AssessmentId")
                        .IsUnique()
                        .HasDatabaseName("ux_ai_analyses_current")
                        .HasFilter("is_current = true");

                    b.HasIndex("AssessmentId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ai_analyses_assessment");

                    b.ToTable("ai_analyses", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Ai.AiProviderConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ApiKeyEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("api_key_encrypted");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("display_name");

                    b.Property<int>("FallbackOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("fallback_order");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("LastCheckStatus")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_check_status");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked_at");

                    b.Property<int>("MaxOutputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4096)
                        .HasColumnName("max_output_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("model");

                    b.Property<short>("Provider")
                        .HasColumnType("smallint")
                        .HasColumnName("provider");

                    b.Property<decimal>("Temperature")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(0.4m)
                        .HasColumnName("temperature");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_ai_provider_configs");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ux_ai_provider_default")
                        .HasFilter("is_default = true");

                    b.HasIndex("Provider")
                        .IsUnique()
                        .HasDatabaseName("ux_ai_provider_kind");

                    b.ToTable("ai_provider_configs", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Ai.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("JsonSchema")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("json_schema");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("SystemText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_text");

                    b.Property<string>("UserText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_prompt_templates");

                    b.HasIndex("Key", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_prompt_templates");

                    b.ToTable("prompt_templates", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Assessments.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("AssessmentTestId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_test_id");

                    b.Property<int>("DurationMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("duration_ms");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<int>("RawValue")
                        .HasColumnType("integer")
                        .HasColumnName("raw_value");

                    b.Property<int>("RevisionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("revision_count");

                    b.Property<Guid?>("SelectedOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_option_id");

                    b.HasKey("Id")
                        .HasName("pk_answers");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_answers_question_id");

                    b.HasIndex("SelectedOptionId")
                        .HasDatabaseName("ix_answers_selected_option_id");

                    b.HasIndex("AssessmentTestId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ux_answers_test_question");

                    b.ToTable("answers", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Assessments.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_hash");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasDefaultValue("uz")
                        .HasColumnName("language_code");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<short?>("ReliabilityFlag")
                        .HasColumnType("smallint")
                        .HasColumnName("reliability_flag");

                    b.Property<decimal?>("ReliabilityScore")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("reliability_score");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("session_token");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<int?>("TotalDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("total_duration_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_assessments");

                    b.HasIndex("ProgramId")
                        .HasDatabaseName("ix_assessments_program");

                    b.HasIndex("SessionToken")
                        .IsUnique()
                        .HasDatabaseName("ux_assessments_token");

                    b.HasIndex("SchoolId", "Status")
                        .HasDatabaseName("ix_assessments_school_status");

                    b.HasIndex("Status", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_assessments_status_started");

                    b.HasIndex("StudentId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_assessments_student");

                    b.ToTable("assessments", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Assessments.AssessmentTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AnsweredCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("answered_count");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("QuestionOrder")
                        .HasColumnType("jsonb")
                        .HasColumnName("question_order_json");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("status");

                    b.Property<Guid>("TestDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_definition_id");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_count");

                    b.HasKey("Id")
                        .HasName("pk_assessment_tests");

                    b.HasIndex("TestDefinitionId")
                        .HasDatabaseName("ix_assessment_tests_test_definition_id");

                    b.HasIndex("AssessmentId", "TestDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ux_assessment_tests");

                    b.ToTable("assessment_tests", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Assessments.TestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<Guid>("AssessmentTestId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_test_id");

                    b.Property<decimal?>("CompositeIndex")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("composite_index");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FlagsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("flags_json")
                        .HasDefaultValueSql("'[]'");

                    b.Property<string>("LevelsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("levels_json")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("NormalizedScoresJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("normalized_scores_json");

                    b.Property<string>("RawScoresJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_scores_json");

                    b.Property<string>("ResultCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result_code");

                    b.Property<int>("ScoringVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("scoring_version");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("test_code");

                    b.Property<int>("TestVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("test_version");

                    b.HasKey("Id")
                        .HasName("pk_test_results");

                    b.HasIndex("AssessmentId")
                        .HasDatabaseName("ix_test_results_assessment");

                    b.HasIndex("AssessmentTestId")
                        .IsUnique()
                        .HasDatabaseName("ux_test_results_test");

                    b.HasIndex("TestCode", "ResultCode")
                        .HasDatabaseName("ix_test_results_code");

                    b.ToTable("test_results", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Catalog.AnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("Scale")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("scale");

                    b.Property<string>("TextUz")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uz");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_answer_options");

                    b.HasIndex("QuestionId", "DisplayOrder")
                        .HasDatabaseName("ix_answer_options_question");

                    b.ToTable("answer_options", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Catalog.AssessmentProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedByAdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_admin_user_id");

                    b.Property<string>("DescriptionUz")
                        .HasColumnType("text")
                        .HasColumnName("description_uz");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<short>("Kind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2)
                        .HasColumnName("kind");

                    b.Property<string>("NameUz")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name_uz");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2)
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_assessment_programs");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_assessment_programs_code");

                    b.HasIndex("IsActive", "DisplayOrder")
                        .HasDatabaseName("ix_assessment_programs_active")
                        .HasFilter("status = 2");

                    b.ToTable("assessment_programs", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Catalog.CareerMapEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("DescriptionUz")
                        .HasColumnType("text")
                        .HasColumnName("description_uz");

                    b.Property<string>("ExampleProfessions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("example_professions_json")
                        .HasDefaultValueSql("'[]'");

                    b.Property<string>("FieldNameUz")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("field_name_uz");

                    b.Property<string>("HollandCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("holland_code");

                    b.Property<int>("RelevanceOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("relevance_order");

                    b.HasKey("Id")
                        .HasName("pk_career_map");

                    b.HasIndex("HollandCode", "RelevanceOrder")
                        .HasDatabaseName("ix_career_map_code");

                    b.ToTable("career_map", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Catalog.ProgramTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<Guid>("TestDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_definition_id");

                    b.HasKey("Id")
                        .HasName("pk_program_tests");

                    b.HasIndex("TestDefinitionId")
                        .HasDatabaseName("ix_program_tests_test_definition_id");

                    b.HasIndex("ProgramId", "DisplayOrder")
                        .HasDatabaseName("ix_program_tests_order");

                    b.HasIndex("ProgramId", "TestDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("ux_program_tests");

                    b.ToTable("program_tests", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Catalog.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<short>("QuestionType")
                        .HasColumnType("smallint")
                        .HasColumnName("question_type");

                    b.Property<string>("Scale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("scale");

                    b.Property<short>("ScaleDirection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("scale_direction");

                    b.Property<Guid>("TestDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_definition_id");

                    b.Property<string>("TextEn")
                        .HasColumnType("text")
                        .HasColumnName("text_en");

                    b.Property<string>("TextRu")
                        .HasColumnType("text")
                        .HasColumnName("text_ru");

                    b.Property<string>("TextUz")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_uz");

                    b.Property<decimal>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(4,2)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_questions_code");

                    b.HasIndex("TestDefinitionId", "DisplayOrder")
                        .HasDatabaseName("ix_questions_test_order");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Catalog.SchoolProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.HasKey("Id")
                        .HasName("pk_school_programs");

                    b.HasIndex("ProgramId")
                        .HasDatabaseName("ix_school_programs_program");

                    b.HasIndex("SchoolId", "ProgramId")
                        .IsUnique()
                        .HasDatabaseName("ux_school_programs");

                    b.ToTable("school_programs", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Catalog.TestDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedByAdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_admin_user_id");

                    b.Property<string>("DescriptionUz")
                        .HasColumnType("text")
                        .HasColumnName("description_uz");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_minutes");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<short>("Kind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("kind");

                    b.Property<string>("NameUz")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name_uz");

                    b.Property<int>("PageSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("page_size");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<short>("ScoringMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("scoring_mode");

                    b.Property<string>("ScoringStrategyCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scoring_strategy");

                    b.Property<bool>("ShuffleQuestions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("shuffle_questions");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)2)
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_definitions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_test_definitions_code");

                    b.HasIndex("IsActive", "DisplayOrder")
                        .HasDatabaseName("ix_test_definitions_active")
                        .HasFilter("status = 2");

                    b.ToTable("test_definitions", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Catalog.TestScale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("DescriptionUz")
                        .HasColumnType("text")
                        .HasColumnName("description_uz");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("InterpretationBands")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("interpretation_bands_json")
                        .HasDefaultValueSql("'[]'");

                    b.Property<string>("NameUz")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name_uz");

                    b.Property<Guid>("TestDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_definition_id");

                    b.HasKey("Id")
                        .HasName("pk_test_scales");

                    b.HasIndex("TestDefinitionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_test_scales");

                    b.ToTable("test_scales", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Catalog.TypeCatalogEntry", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("code");

                    b.Property<string>("CareerHints")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("career_hints_json")
                        .HasDefaultValueSql("'[]'");

                    b.Property<string>("GrowthAreas")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("growth_areas_json")
                        .HasDefaultValueSql("'[]'");

                    b.Property<string>("LongDescriptionUz")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("long_description_uz");

                    b.Property<string>("NameUz")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name_uz");

                    b.Property<string>("ShortDescriptionUz")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("short_description_uz");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("strengths_json")
                        .HasDefaultValueSql("'[]'");

                    b.HasKey("Code")
                        .HasName("pk_type_catalog");

                    b.ToTable("type_catalog", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Identity.AdminTotpBackupCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_admin_totp_backup_codes");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_admin_totp_backup_codes_admin");

                    b.ToTable("admin_totp_backup_codes", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Identity.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("EmailLower")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("email_lower")
                        .HasComputedColumnSql("lower(email)", true);

                    b.Property<int>("FailedLoginCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("password_hash");

                    b.Property<short>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("role");

                    b.Property<bool>("TotpEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("totp_enabled");

                    b.Property<long?>("TotpLastUsedStep")
                        .HasColumnType("bigint")
                        .HasColumnName("totp_last_used_step");

                    b.Property<string>("TotpSecretEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("totp_secret_encrypted");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("username");

                    b.Property<string>("UsernameLower")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("username_lower")
                        .HasComputedColumnSql("lower(username)", true);

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.HasIndex("EmailLower")
                        .IsUnique()
                        .HasDatabaseName("ux_admin_users_email");

                    b.HasIndex("UsernameLower")
                        .IsUnique()
                        .HasDatabaseName("ux_admin_users_username");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Identity.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_audit_logs_admin_user_id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_audit_logs_created");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedByIpHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip_hash");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_refresh_tokens_admin_user_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_hash");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Jobs.AnalysisJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("RequestedPromptVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("requested_prompt_version");

                    b.Property<short?>("RequestedProvider")
                        .HasColumnType("smallint")
                        .HasColumnName("requested_provider");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_analysis_jobs");

                    b.HasIndex("AssessmentId")
                        .IsUnique()
                        .HasDatabaseName("ux_analysis_jobs_active_per_assessment")
                        .HasFilter("status IN (0, 1)");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_analysis_jobs_status");

                    b.ToTable("analysis_jobs", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Schools.RegistrationCounter", b =>
                {
                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<DateOnly>("DateUtc")
                        .HasColumnType("date")
                        .HasColumnName("date_utc");

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("count");

                    b.HasKey("SchoolId", "DateUtc")
                        .HasName("pk_registration_counters");

                    b.ToTable("registration_counters", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Schools.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("access_code");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("access_token");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("contact_person");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DailyRegistrationLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(500)
                        .HasColumnName("daily_registration_limit");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("district");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<string>("SchoolNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("school_number");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_schools");

                    b.HasIndex("AccessToken")
                        .IsUnique()
                        .HasDatabaseName("ux_schools_token");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_schools_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_schools_slug")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("Region", "District")
                        .HasDatabaseName("ix_schools_region_dist");

                    b.ToTable("schools", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Schools.SchoolLinkView", b =>
                {
                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<DateOnly>("DateUtc")
                        .HasColumnType("date")
                        .HasColumnName("date_utc");

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("count");

                    b.HasKey("SchoolId", "DateUtc")
                        .HasName("pk_school_link_views");

                    b.ToTable("school_link_views", (string)null);
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("ClassLetter")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("class_letter");

                    b.Property<int>("CompletedAssessmentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("completed_assessment_count");

                    b.Property<DateTimeOffset>("ConsentGivenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consent_given_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<short>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("gender");

                    b.Property<int>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<decimal?>("LastActivityIndex")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("last_activity_index");

                    b.Property<short?>("LastActivityLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("last_activity_level");

                    b.Property<DateTimeOffset?>("LastAssessmentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_assessment_at");

                    b.Property<string>("LastHollandCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("last_holland_code");

                    b.Property<decimal?>("LastMaturityIndex")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("last_maturity_index");

                    b.Property<string>("LastPersonalityType")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("last_personality_type");

                    b.Property<bool>("NeedsAttention")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("needs_attention");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("ParentPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("parent_phone");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("school_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex("FullName")
                        .HasDatabaseName("ix_students_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FullName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("FullName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("LastAssessmentAt")
                        .IsDescending()
                        .HasDatabaseName("ix_students_last_at");

                    b.HasIndex("NeedsAttention")
                        .HasDatabaseName("ix_students_attention")
                        .HasFilter("needs_attention = true");

                    b.HasIndex("SchoolId", "Grade")
                        .HasDatabaseName("ix_students_school_grade");

                    b.HasIndex("SchoolId", "NormalizedName", "BirthDate")
                        .IsUnique()
                        .HasDatabaseName("ux_students_identity")
                        .HasFilter("is_deleted = false");

                    b.ToTable("students", null, t =>
                        {
                            t.HasCheckConstraint("ck_students_grade", "grade BETWEEN 1 AND 11");
                        });
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Ai.AiAnalysis", b =>
                {
                    b.HasOne("StudentRoadMap.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_analyses_assessments_assessment_id");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Assessments.Answer", b =>
                {
                    b.HasOne("StudentRoadMap.Domain.Assessments.AssessmentTest", null)
                        .WithMany("Answers")
                        .HasForeignKey("AssessmentTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answers_assessment_tests_assessment_test_id");

                    b.HasOne("StudentRoadMap.Domain.Catalog.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_answers_questions_question_id");

                    b.HasOne("StudentRoadMap.Domain.Catalog.AnswerOption", null)
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_answers_answer_options_selected_option_id");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Assessments.Assessment", b =>
                {
                    b.HasOne("StudentRoadMap.Domain.Catalog.AssessmentProgram", null)
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assessments_assessment_programs_program_id");

                    b.HasOne("StudentRoadMap.Domain.Schools.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assessments_schools_school_id");

                    b.HasOne("StudentRoadMap.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessments_students_student_id");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Assessments.AssessmentTest", b =>
                {
                    b.HasOne("StudentRoadMap.Domain.Assessments.Assessment", null)
                        .WithMany("Tests")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assessment_tests_assessments_assessment_id");

                    b.HasOne("StudentRoadMap.Domain.Catalog.TestDefinition", null)
                        .WithMany()
                        .HasForeignKey("TestDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assessment_tests_test_definitions_test_definition_id");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Assessments.TestResult", b =>
                {
                    b.HasOne("StudentRoadMap.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_results_assessments_assessment_id");

                    b.HasOne("StudentRoadMap.Domain.Assessments.AssessmentTest", null)
                        .WithMany()
                        .HasForeignKey("AssessmentTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_results_assessment_tests_assessment_test_id");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Catalog.AnswerOption", b =>
                {
                    b.HasOne("StudentRoadMap.Domain.Catalog.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answer_options_questions_question_id");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Catalog.ProgramTest", b =>
                {
                    b.HasOne("StudentRoadMap.Domain.Catalog.AssessmentProgram", null)
                        .WithMany("Tests")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_program_tests_assessment_programs_program_id");

                    b.HasOne("StudentRoadMap.Domain.Catalog.TestDefinition", null)
                        .WithMany()
                        .HasForeignKey("TestDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_program_tests_test_definitions_test_definition_id");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Catalog.Question", b =>
                {
                    b.HasOne("StudentRoadMap.Domain.Catalog.TestDefinition", null)
                        .WithMany("Questions")
                        .HasForeignKey("TestDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_test_definitions_test_definition_id");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Catalog.SchoolProgram", b =>
                {
                    b.HasOne("StudentRoadMap.Domain.Catalog.AssessmentProgram", null)
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_school_programs_assessment_programs_program_id");

                    b.HasOne("StudentRoadMap.Domain.Schools.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_school_programs_schools_school_id");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Catalog.TestScale", b =>
                {
                    b.HasOne("StudentRoadMap.Domain.Catalog.TestDefinition", null)
                        .WithMany("Scales")
                        .HasForeignKey("TestDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_scales_test_definitions_test_definition_id");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Identity.AdminTotpBackupCode", b =>
                {
                    b.HasOne("StudentRoadMap.Domain.Identity.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_totp_backup_codes_admin_users_admin_user_id");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Identity.AuditLog", b =>
                {
                    b.HasOne("StudentRoadMap.Domain.Identity.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_logs_admin_users_admin_user_id");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("StudentRoadMap.Domain.Identity.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_admin_users_admin_user_id");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Jobs.AnalysisJob", b =>
                {
                    b.HasOne("StudentRoadMap.Domain.Assessments.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_jobs_assessments_assessment_id");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Schools.RegistrationCounter", b =>
                {
                    b.HasOne("StudentRoadMap.Domain.Schools.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_registration_counters_schools_school_id");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Schools.SchoolLinkView", b =>
                {
                    b.HasOne("StudentRoadMap.Domain.Schools.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_school_link_views_schools_school_id");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Students.Student", b =>
                {
                    b.HasOne("StudentRoadMap.Domain.Schools.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_students_schools_school_id");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Assessments.Assessment", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Assessments.AssessmentTest", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Catalog.AssessmentProgram", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Catalog.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("StudentRoadMap.Domain.Catalog.TestDefinition", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Scales");
                });
#pragma warning restore 612, 618
        }
    }
}
